---
name: pre-commit
on:
  pull_request:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      LOG_TO_CS: .github/logToCs.py
      RAW_LOG: pre-commit.log
      CS_XML: pre-commit.xml
    steps:
      - run: sudo apt-get update && sudo apt-get install cppcheck
        if: false
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        if: false
        with:
          cache: pip
          python-version: "3.12.1"
      - run: python -m pip install pre-commit
      - uses: actions/cache/restore@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml')
            }}
      - name: Run pre-commit hooks
        env:
          SKIP: no-commit-to-branch
        run: |
          set -o pipefail
          pre-commit run --show-diff-on-failure --color=always --all-files | tee ${RAW_LOG}
      - name: Convert Raw Log to CheckStyle format
        if: ${{ failure() }}
        run: |
          ${LOG_TO_CS} ${RAW_LOG} ${CS_XML}
      - name: Annotate Source Code with Messages
        uses: staabm/annotate-pull-request-from-checkstyle-action@v1
        if: ${{ failure() }}
        with:
          files: ${{ env.CS_XML }}
          notices-as-warnings: true # optional
          prepend-filename: true # optional
      - uses: actions/cache/save@v3
        if: ${{ always() }}
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml')
            }}
